---
sudo: required
dist: trusty
language: generic

env:
  - PLAYBOOK=test.yml

before_install:
  - sudo apt-get update -qq

install:
  # install ansible
  - sudo pip install ansible

  # configure ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # check syntax
  - "ansible-playbook -i tests/inventory tests/$PLAYBOOK --syntax-check"

  # initial run
  - "ansible-playbook -i tests/inventory tests/$PLAYBOOK --connection=local --sudo"

  # check idempotence
  - "ansible-playbook -i tests/inventory tests/$PLAYBOOK --connection=local --sudo"
  